"""add_turnos

Revision ID: 1d3b0253c8ce
Revises: 2c196b5b4d21
Create Date: 2026-06-17 16:17:39.945373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3b0253c8ce'
down_revision: Union[str, None] = '2c196b5b4d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_parameters', sa.Column('turnos', sa.JSON(), nullable=True))
    op.add_column('tenant_parameters', sa.Column('turnos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_parameters', 'turnos')
    op.drop_column('global_parameters', 'turnos')
    # ### end Alembic commands ###
