"""add_subject_allowed_turnos

Revision ID: 3e2f7d8a9c1b
Revises: 1d3b0253c8ce
Create Date: 2026-06-17 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f7d8a9c1b'
down_revision: Union[str, None] = '1d3b0253c8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('allowed_turnos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'allowed_turnos')
    # ### end Alembic commands ###
