"""add_offer_insights

Revision ID: d7e5f7ccd037
Revises: 3e2f7d8a9c1b
Create Date: 2026-06-17 18:05:15.197577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e5f7ccd037'
down_revision: Union[str, None] = '3e2f7d8a9c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'insights')
    # ### end Alembic commands ###
